version: "3.8"

services:
  snapmeet-server:
    build:
      context: ./server
      target: dev
    container_name: snapmeet-server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: always
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}

  snapmeet-client:
    build:
      context: ./client
      target: dev
    container_name: snapmeet-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: always
